<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Jamaah extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jamaah_model');
        $this->load->model('Scan_model');
    }

    /*
     * Listing of luasan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('jamaah/index?');
        $config['total_rows'] = $this->Jamaah_model->get_all_jamaah_count();
        $this->pagination->initialize($config);

        $user_level = $this->session->userdata('user_level');
        $user_id = $this->session->userdata('user_id');
        // $data['jamaah'] = $this->Jamaah_model->get_all_jamaah($params);

        $data['jamaah'] = '';
        if ($user_level == '2') {
            $data['jamaah'] = $this->Jamaah_model->get_all_jamaah_by_cabang($user_id);
        } elseif ($user_level == '1') {
            $data['jamaah'] = $this->Jamaah_model->get_all_jamaah($params);
        }

        $data['_view'] = 'jamaah/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new luasan
     */

    function bukatambah()
    {
        $data['_view'] = 'jamaah/add';
        $this->load->view('layouts/main', $data);
    }
    function add()
    {
        $config['upload_path'] = './assets/images/'; //path folder
        $config['allowed_types'] = 'gif|jpg|png|jpeg|bmp'; //type yang dapat diakses bisa anda sesuaikan
        $config['encrypt_name'] = TRUE; //nama yang terupload nantinya
        $user_id = $this->session->userdata('user_id');
        $this->load->library('ciqrcode');

        $this->upload->initialize($config);
        if (!empty($_FILES['jamaah_img']['name'])) {
            if ($this->upload->do_upload('jamaah_img')) {
                $gbr = $this->upload->data();
                //Compress Image
                $config['image_library'] = 'gd2';
                $config['source_image'] = './assets/images/' . $gbr['file_name'];
                $config['create_thumb'] = FALSE;
                $config['maintain_ratio'] = FALSE;
                $config['quality'] = '60%';
                $config['width'] = '20%';
                $config['max_size'] = '10000';
                $config['new_image'] = './assets/images/' . $gbr['file_name'];
                $this->load->library('image_lib', $config);
                $this->image_lib->resize();
                $gambar = $gbr['file_name'];

                $params = array(
                    'nik' => $this->input->post('nik'),
                    'nama_jamaah' => $this->input->post('nama_jamaah'),
                    'jenis_kelamin' => $this->input->post('jenis_kelamin'),
                    'nomor_telepon' => $this->input->post('nomor_telepon'),
                    'grup_keberangkatan' => $this->input->post('grup_keberangkatan'),
                    'paket' => $this->input->post('paket'),
                    'alamat' => $this->input->post('alamat'),
                    'nomor_paspor' => $this->input->post('nomor_paspor'),
                    'created_by' => $user_id,
                );

                $config['cacheable']    = true; //boolean, the default is true
                $config['cachedir']     = './assets/'; //string, the default is application/cache/
                $config['errorlog']     = './assets/'; //string, the default is application/logs/
                $config['imagedir']     = './assets/images/qr/'; //direktori penyimpanan qr code
                $config['quality']      = true; //boolean, the default is true
                $config['size']         = '1024'; //interger, the default is 1024
                $config['black']        = array(224, 255, 255); // array, default is array(255,255,255)
                $config['white']        = array(70, 130, 180); // array, default is array(0,0,0)
                $this->ciqrcode->initialize($config);

                $nama = $this->input->post('nik');

                $qr_code = $nama . '.png'; //buat name dari qr code sesuai dengan nim

                $params['data'] = $nama; //data yang akan di jadikan QR CODE
                $params['level'] = 'H'; //H=High
                $params['size'] = 10;
                $params['savename'] = FCPATH . $config['imagedir'] . $qr_code; //simpan image QR CODE ke folder assets/images/
                $this->ciqrcode->generate($params); // fungsi untuk generate QR CODE

                $this->Jamaah_model->add_jamaah($params, $qr_code, $gambar);
                redirect('jamaah/index');
            } else {
                echo "else";
                exit();
                redirect('jamaah/index');
            }
        } else {
            $this->session->set_flashdata('error', 'Ukuran Tidak boleh lebih dari 5 MB');
            redirect('jamaah/add');
        }

        // $user_id = $this->session->userdata('user_id');
        // if (isset($_POST) && count($_POST) > 0) {
        //     $params = array(
        //         'nama_program' => $this->input->post('nama_program'),
        //         'jamaah' => $this->input->post('jamaah'),
        //         'hotel_mekkah' => $this->input->post('hotel_mekkah'),
        //         'hotel_madinah' => $this->input->post('hotel_madinah'),
        //         'bintang_mekkah' => $this->input->post('bintang_mekkah'),
        //         'bintang_madinah' => $this->input->post('bintang_madinah'),
        //         'uang_muka' => $this->input->post('uang_muka'),
        //         'harga_jamaah' => $this->input->post('harga_jamaah'),
        //         'sudah_termasuk' => $this->input->post('sudah_termasuk'),
        //         'belum_termasuk' => $this->input->post('belum_termasuk'),
        //         'jamaah_img' => $this->input->post('jamaah_img'),
        //         'created_by' => $user_id,
        //     );
        //     $jamaah_id = $this->Jamaah_model->add_jamaah($params);
        //     redirect('jamaah/index');
        // } else {
        //     $data['_view'] = 'jamaah/add';
        //     $this->load->view('layouts/main', $data);
        // }
    }
    /*
     * Editing a luasan
     */
    function edit($id_jamaah)
    {
        // check if the luasan exists before trying to edit it
        $data['jamaah'] = $this->Jamaah_model->get_jamaah($id_jamaah);

        if (isset($data['jamaah']['id_jamaah'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'nik' => $this->input->post('nik'),
                    'nama_jamaah' => $this->input->post('nama_jamaah'),
                    'jenis_kelamin' => $this->input->post('jenis_kelamin'),
                    'nomor_telepon' => $this->input->post('nomor_telepon'),
                    'grup_keberangkatan' => $this->input->post('grup_keberangkatan'),
                    'paket' => $this->input->post('paket'),
                    'alamat' => $this->input->post('alamat'),
                    'nomor_paspor' => $this->input->post('nomor_paspor'),
                );

                $this->Jamaah_model->update_jamaah($id_jamaah, $params);
                redirect('jamaah/index');
            } else {
                $data['_view'] = 'jamaah/edit';
                $this->load->view('layouts/main', $data);
            }
        } else {
            show_error('The jamaah you are trying to edit does not exist.');
        }
    }

    function cetak_id_card($id_jamaah)
    {
        // check if the luasan exists before trying to edit it
        $data['jamaah'] = $this->Jamaah_model->get_jamaah($id_jamaah);

        if (isset($data['jamaah']['id_jamaah'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'qr_code' => $this->input->post('qr_code'),
                    'nama_jamaah' => $this->input->post('nama_jamaah'),
                );

                $this->Jamaah_model->update_jamaah($id_jamaah, $params);
                redirect('jamaah/index');
            } else {
                $data['_view'] = 'jamaah/cetak';
                $this->load->view('layouts/main', $data);
            }
        } else {
            show_error('The jamaah you are trying to edit does not exist.');
        }

        // if (isset($data['jamaah']['id_jamaah'])) {
        //     if (isset($_POST) && count($_POST) > 0) {
        //         $params = array(
        //             'nik' => $this->input->post('nik'),
        //             'nama_jamaah' => $this->input->post('nama_jamaah'),
        //             'jamaah_img' => $this->input->post('jamaah_img'),
        //         );

        //         $this->Jamaah_model->update_jamaah($id_jamaah, $params);
        //         redirect('jamaah/index');
        //     } else {
        //         $data['_view'] = 'jamaah/index';
        //         $this->load->view('layouts/main', $data);
        //     }
        // } else
        //     show_error('The jamaah you are trying to edit does not exist.');
    }

    function edit_kehadiran($id_jamaah)
    {
        // check if the luasan exists before trying to edit it
        $data['jamaah'] = $this->Jamaah_model->get_jamaah($id_jamaah);

        if (isset($data['jamaah']['id_jamaah'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'kehadiran' => 'Tidak Hadir / Belum Hadir',
                );

                $this->Jamaah_model->update_jamaah($id_jamaah, $params);
                redirect('jamaah/index');
            } else {
                $data['_view'] = 'jamaah/index';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The jamaah you are trying to edit does not exist.');
    }

    /*
     * Deleting jamaah
     */
    function remove($id_jamaah)
    {
        $jamaah = $this->Jamaah_model->get_jamaah($id_jamaah);

        // check if the jamaah exists before trying to delete it
        if (isset($jamaah['id_jamaah'])) {
            $this->Jamaah_model->delete_jamaah($id_jamaah);
            redirect('jamaah/index');
        } else
            show_error('The jamaah you are trying to delete does not exist.');
    }
}
