<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class kategori extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('Kategori_model');
        $this->load->model('Users_model');
    }

    /*
     * Listing of kategori
     */
    public function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('kategori/index?');
        $config['total_rows'] = $this->Kategori_model->get_all_kategori_count();
        $this->pagination->initialize($config);

        $user_level = $this->session->userdata('user_level');
        $user_id = $this->session->userdata('user_id');

        $data['kategori'] = $this->Kategori_model->get_all_kategori($params);

        $data['_view'] = 'kategori/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new kategori
     */
    public function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'nama_kategori' => $this->input->post('nama_kategori'),
            );

            $id_kategori = $this->Kategori_model->add_kategori($params);
            redirect('kategori/index');
        } else {
            $data['_view'] = 'kategori/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a kategori
     */

    public function edit($id_kategori)
    {
        // check if the kategori exists before trying to edit it
        $data['kategori'] = $this->Kategori_model->get_kategori($id_kategori);

        if (isset($data['kategori']['id_kategori'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'nama_kategori' => $this->input->post('nama_kategori'),
                );

                $this->Kategori_model->update_kategori($id_kategori, $params);
                redirect('kategori/index');
            } else {
                $data['_view'] = 'kategori/edit';
                $this->load->view('layouts/main', $data);
            }
        } else {
            show_error('The kategori you are trying to edit does not exist.');
        }

    }

    /*
     * Deleting kategori
     */
    public function remove($id_kategori)
    {
        $kategori = $this->Kategori_model->get_kategori($id_kategori);

        // check if the kategori exists before trying to delete it
        if (isset($kategori['id_kategori'])) {
            $this->Kategori_model->delete_kategori($id_kategori);
            redirect('kategori/index');
        } else {
            show_error('The kategori you are trying to delete does not exist.');
        }

    }
}