<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Keberangkatan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Keberangkatan_model');
        $this->load->model('Users_model');
    }

    /*
     * Listing of keberangkatan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('keberangkatan/index?');
        $config['total_rows'] = $this->Keberangkatan_model->get_all_keberangkatan_count();
        $this->pagination->initialize($config);

        $user_level = $this->session->userdata('user_level');
        $user_id = $this->session->userdata('user_id');

        $data['keberangkatan'] = '';
        if ($user_level == '2') {
            $data['keberangkatan'] = $this->Keberangkatan_model->get_users_by_created_by($user_id);
        } elseif ($user_level == '1') {
            $data['keberangkatan'] = $this->Keberangkatan_model->get_all_keberangkatan($params);
        }


        // echo '<pre>';
        // print_r($data['keberangkatan']);
        // exit();

        $data['_view'] = 'keberangkatan/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new keberangkatan
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'tanggal_keberangkatan' => $this->input->post('tanggal_keberangkatan'),
                'paket' => $this->input->post('paket'),
                'lama_hari' => $this->input->post('lama_hari'),
                'hotel_mekkah' => $this->input->post('hotel_mekkah'),
                'hotel_madinah' => $this->input->post('hotel_madinah'),
                'is_aktif' => $this->input->post('is_aktif'),
            );

            $keberangkatan_id = $this->Keberangkatan_model->add_keberangkatan($params);
            redirect('keberangkatan/index');
        } else {
            $data['_view'] = 'keberangkatan/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a keberangkatan
     */


    function edit($id_keberangkatan)
    {
        // check if the keberangkatan exists before trying to edit it
        $data['keberangkatan'] = $this->Keberangkatan_model->get_keberangkatan($id_keberangkatan);

        if (isset($data['keberangkatan']['id_keberangkatan'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'tanggal_keberangkatan' => $this->input->post('tanggal_keberangkatan'),
                    'paket' => $this->input->post('paket'),
                    'lama_hari' => $this->input->post('lama_hari'),
                    'hotel_mekkah' => $this->input->post('hotel_mekkah'),
                    'hotel_madinah' => $this->input->post('hotel_madinah'),
                    'is_aktif' => $this->input->post('is_aktif'),

                );

                $this->Keberangkatan_model->update_keberangkatan($id_keberangkatan, $params);
                redirect('keberangkatan/index');
            } else {
                $data['_view'] = 'keberangkatan/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The keberangkatan you are trying to edit does not exist.');
    }

    /*
     * Deleting keberangkatan
     */
    function remove($id_keberangkatan)
    {
        $keberangkatan = $this->Keberangkatan_model->get_keberangkatan($id_keberangkatan);

        // check if the keberangkatan exists before trying to delete it
        if (isset($keberangkatan['id_keberangkatan'])) {
            $this->Keberangkatan_model->delete_keberangkatan($id_keberangkatan);
            redirect('keberangkatan/index');
        } else
            show_error('The keberangkatan you are trying to delete does not exist.');
    }
}
