<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Petani extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Petani_model');
        $this->load->model('Users_model');
    }

    /*
     * Listing of petani
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('petani/index?');
        $config['total_rows'] = $this->Petani_model->get_all_petani_count();
        $this->pagination->initialize($config);

        $user_level = $this->session->userdata('user_level');
        $user_id = $this->session->userdata('user_id');

        $data['petani'] = '';
        if ($user_level == '2') {
            $data['petani'] = $this->Petani_model->get_users_by_created_by($user_id);
        } elseif ($user_level == '1') {
            $data['petani'] = $this->Petani_model->get_all_petani($params);
        }


        // echo '<pre>';
        // print_r($data['petani']);
        // exit();

        $data['_view'] = 'petani/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new petani
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'jenis_kelamin' => $this->input->post('jenis_kelamin'),
                'nama_petani' => $this->input->post('nama_petani'),
                'tanggal_lahir' => $this->input->post('tanggal_lahir'),
                'pendidikan_terakhir' => $this->input->post('pendidikan_terakhir'),
                'nik' => $this->input->post('nik'),
                'nomor_hp' => $this->input->post('nomor_hp'),
                'alamat' => $this->input->post('alamat'),
                'is_akun' => '0',
            );

            $petani_id = $this->Petani_model->add_petani($params);
            redirect('petani/index');
        } else {
            $data['_view'] = 'petani/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a petani
     */


    function edit($id_petani)
    {
        // check if the petani exists before trying to edit it
        $data['petani'] = $this->Petani_model->get_petani($id_petani);

        if (isset($data['petani']['id_petani'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'jenis_kelamin' => $this->input->post('jenis_kelamin'),
                    'nama_petani' => $this->input->post('nama_petani'),
                    'tanggal_lahir' => $this->input->post('tanggal_lahir'),
                    'pendidikan_terakhir' => $this->input->post('pendidikan_terakhir'),
                    'nik' => $this->input->post('nik'),
                    'nomor_hp' => $this->input->post('nomor_hp'),
                    'alamat' => $this->input->post('alamat'),
                );

                $this->Petani_model->update_petani($id_petani, $params);
                redirect('petani/index');
            } else {
                $data['_view'] = 'petani/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The petani you are trying to edit does not exist.');
    }

    /*
     * Deleting petani
     */
    function remove($id_petani)
    {
        $petani = $this->Petani_model->get_petani($id_petani);

        // check if the petani exists before trying to delete it
        if (isset($petani['id_petani'])) {
            $this->Petani_model->delete_petani($id_petani);
            redirect('petani/index');
        } else
            show_error('The petani you are trying to delete does not exist.');
    }

    public function proses($id_petani)
    {
        $data['petani'] = $this->Petani_model->get_petani($id_petani);
        $this->form_validation->set_rules('user_name', 'user_name', 'trim|required|min_length[1]|max_length[255]');
        $this->form_validation->set_rules('user_password', 'user_password', 'trim|required|min_length[1]|max_length[255]');
        $this->form_validation->set_rules('user_email', 'user_email', 'trim|required|min_length[1]|max_length[255]|is_unique[tbl_users.user_email]');
        if ($this->form_validation->run() == true) {
            $params = array(
                'user_level' => '3',
                'id_petani' => $data['petani']['id_petani'],
                'user_name' => $data['petani']['nama_petani'],
                'user_email' => $this->input->post('user_email'),
                'user_password' => md5($this->input->post('user_password')),
                'is_akun' => '1',
            );
            $this->Petani_model->register($id_petani, $params);
            $this->session->set_flashdata('success_register', 'Proses Pendaftaran User Berhasil');
            redirect('petani/index');
        } else {
            $this->session->set_flashdata('error', 'Proses Tidak Berhasil. Pastikan Username anda tidak sama dengan yang sudah ada');
            redirect('petani/index');
        }
    }

    public function export()
    {
        // Load plugin PHPExcel nya
        include APPPATH . 'third_party/PHPExcel/PHPExcel.php';

        // Panggil class PHPExcel nya
        $excel = new PHPExcel();

        // Settingan awal fil excel
        $excel->getProperties()->setCreator('BPP Bumiaji')
            ->setLastModifiedBy('BPP Bumiaji')
            ->setTitle("Data Petani")
            ->setSubject("Petani")
            ->setDescription("Laporan Semua Data Petani")
            ->setKeywords("Data Petani");

        // Buat sebuah variabel untuk menampung pengaturan style dari header tabel
        $style_col = array(
            'font' => array('bold' => true), // Set font nya jadi bold
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER, // Set text jadi ditengah secara horizontal (center)
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER // Set text jadi di tengah secara vertical (middle)
            ),
            'borders' => array(
                'top' => array('style'  => PHPExcel_Style_Border::BORDER_THIN), // Set border top dengan garis tipis
                'right' => array('style'  => PHPExcel_Style_Border::BORDER_THIN),  // Set border right dengan garis tipis
                'bottom' => array('style'  => PHPExcel_Style_Border::BORDER_THIN), // Set border bottom dengan garis tipis
                'left' => array('style'  => PHPExcel_Style_Border::BORDER_THIN) // Set border left dengan garis tipis
            )
        );

        // Buat sebuah variabel untuk menampung pengaturan style dari isi tabel
        $style_row = array(
            'alignment' => array(
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER // Set text jadi di tengah secara vertical (middle)
            ),
            'borders' => array(
                'top' => array('style'  => PHPExcel_Style_Border::BORDER_THIN), // Set border top dengan garis tipis
                'right' => array('style'  => PHPExcel_Style_Border::BORDER_THIN),  // Set border right dengan garis tipis
                'bottom' => array('style'  => PHPExcel_Style_Border::BORDER_THIN), // Set border bottom dengan garis tipis
                'left' => array('style'  => PHPExcel_Style_Border::BORDER_THIN) // Set border left dengan garis tipis
            )
        );

        $excel->setActiveSheetIndex(0)->setCellValue('A1', "DATA PETANI"); // Set kolom A1 dengan tulisan "DATA SISWA"
        $excel->getActiveSheet()->mergeCells('A1:E1'); // Set Merge Cell pada kolom A1 sampai E1
        $excel->getActiveSheet()->getStyle('A1')->getFont()->setBold(TRUE); // Set bold kolom A1
        $excel->getActiveSheet()->getStyle('A1')->getFont()->setSize(15); // Set font size 15 untuk kolom A1
        $excel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER); // Set text center untuk kolom A1

        // Buat header tabel nya pada baris ke 3
        $excel->setActiveSheetIndex(0)->setCellValue('A3', "NO"); // Set kolom A3 dengan tulisan "NO"
        $excel->setActiveSheetIndex(0)->setCellValue('B3', "ID PETANI"); // Set kolom B3 dengan tulisan "NIS"
        $excel->setActiveSheetIndex(0)->setCellValue('C3', "NAMA PETANI"); // Set kolom C3 dengan tulisan "NAMA"
        $excel->setActiveSheetIndex(0)->setCellValue('D3', "TANGGAL LAHIR"); // Set kolom D3 dengan tulisan "JENIS KELAMIN"
        $excel->setActiveSheetIndex(0)->setCellValue('E3', "NIK"); // Set kolom E3 dengan tulisan "ALAMAT"
        $excel->setActiveSheetIndex(0)->setCellValue('F3', "NOMOR HP"); // Set kolom E3 dengan tulisan "ALAMAT"
        $excel->setActiveSheetIndex(0)->setCellValue('G3', "ALAMAT"); // Set kolom E3 dengan tulisan "ALAMAT"
        $excel->setActiveSheetIndex(0)->setCellValue('H3', "JENIS KELAMIN"); // Set kolom E3 dengan tulisan "ALAMAT"
        $excel->setActiveSheetIndex(0)->setCellValue('I3', "PENDIDIKAN TERAKHIR"); // Set kolom E3 dengan tulisan "ALAMAT"
        $excel->setActiveSheetIndex(0)->setCellValue('J3', "SUDAH MENJADI AKUN ?"); // Set kolom E3 dengan tulisan "ALAMAT"

        // Apply style header yang telah kita buat tadi ke masing-masing kolom header
        $excel->getActiveSheet()->getStyle('A3')->applyFromArray($style_col);
        $excel->getActiveSheet()->getStyle('B3')->applyFromArray($style_col);
        $excel->getActiveSheet()->getStyle('C3')->applyFromArray($style_col);
        $excel->getActiveSheet()->getStyle('D3')->applyFromArray($style_col);
        $excel->getActiveSheet()->getStyle('E3')->applyFromArray($style_col);
        $excel->getActiveSheet()->getStyle('F3')->applyFromArray($style_col);
        $excel->getActiveSheet()->getStyle('G3')->applyFromArray($style_col);
        $excel->getActiveSheet()->getStyle('H3')->applyFromArray($style_col);
        $excel->getActiveSheet()->getStyle('I3')->applyFromArray($style_col);
        $excel->getActiveSheet()->getStyle('J3')->applyFromArray($style_col);

        // Panggil function view yang ada di SiswaModel untuk menampilkan semua data siswanya
        $user_level = $this->session->userdata('user_level');
        $user_id = $this->session->userdata('user_id');        
        if ($user_level == '2') {
            $petani = $this->Petani_model->get_users_by_created_by($user_id);
        } elseif ($user_level == '1') {
            $petani = $this->Petani_model->get_all_petani();
        }

        $no = 1; // Untuk penomoran tabel, di awal set dengan 1
        $numrow = 4; // Set baris pertama untuk isi tabel adalah baris ke 4
        foreach ($petani as $data) { // Lakukan looping pada variabel siswa
            $excel->setActiveSheetIndex(0)->setCellValue('A' . $numrow, $no);
            $excel->setActiveSheetIndex(0)->setCellValue('B' . $numrow, $data['id_petani']);
            $excel->setActiveSheetIndex(0)->setCellValue('C' . $numrow, $data['nama_petani']);
            $excel->setActiveSheetIndex(0)->setCellValue('D' . $numrow, $data['tanggal_lahir']);
            $excel->setActiveSheetIndex(0)->setCellValue('E' . $numrow, $data['nik']);
            $excel->setActiveSheetIndex(0)->setCellValue('F' . $numrow, $data['nomor_hp']);
            $excel->setActiveSheetIndex(0)->setCellValue('G' . $numrow, $data['alamat']);
            $excel->setActiveSheetIndex(0)->setCellValue('H' . $numrow, $data['jenis_kelamin']);
            $excel->setActiveSheetIndex(0)->setCellValue('I' . $numrow, $data['pendidikan_terakhir']);
            $excel->setActiveSheetIndex(0)->setCellValue('J' . $numrow, $data['is_akun']);

            // Apply style row yang telah kita buat tadi ke masing-masing baris (isi tabel)
            $excel->getActiveSheet()->getStyle('A' . $numrow)->applyFromArray($style_row);
            $excel->getActiveSheet()->getStyle('B' . $numrow)->applyFromArray($style_row);
            $excel->getActiveSheet()->getStyle('C' . $numrow)->applyFromArray($style_row);
            $excel->getActiveSheet()->getStyle('D' . $numrow)->applyFromArray($style_row);
            $excel->getActiveSheet()->getStyle('E' . $numrow)->applyFromArray($style_row);
            $excel->getActiveSheet()->getStyle('F' . $numrow)->applyFromArray($style_row);
            $excel->getActiveSheet()->getStyle('G' . $numrow)->applyFromArray($style_row);
            $excel->getActiveSheet()->getStyle('H' . $numrow)->applyFromArray($style_row);
            $excel->getActiveSheet()->getStyle('I' . $numrow)->applyFromArray($style_row);
            $excel->getActiveSheet()->getStyle('J' . $numrow)->applyFromArray($style_row);

            $no++; // Tambah 1 setiap kali looping
            $numrow++; // Tambah 1 setiap kali looping
        }

        // Set width kolom
        $excel->getActiveSheet()->getColumnDimension('A')->setWidth(5); // Set width kolom A
        $excel->getActiveSheet()->getColumnDimension('B')->setWidth(15); // Set width kolom B
        $excel->getActiveSheet()->getColumnDimension('C')->setWidth(25); // Set width kolom C
        $excel->getActiveSheet()->getColumnDimension('D')->setWidth(20); // Set width kolom D
        $excel->getActiveSheet()->getColumnDimension('E')->setWidth(30); // Set width kolom E
        $excel->getActiveSheet()->getColumnDimension('F')->setWidth(30); // Set width kolom E
        $excel->getActiveSheet()->getColumnDimension('G')->setWidth(30); // Set width kolom E
        $excel->getActiveSheet()->getColumnDimension('H')->setWidth(30); // Set width kolom E
        $excel->getActiveSheet()->getColumnDimension('I')->setWidth(30); // Set width kolom E
        $excel->getActiveSheet()->getColumnDimension('J')->setWidth(30); // Set width kolom E

        // Set height semua kolom menjadi auto (mengikuti height isi dari kolommnya, jadi otomatis)
        $excel->getActiveSheet()->getDefaultRowDimension()->setRowHeight(-1);

        // Set orientasi kertas jadi LANDSCAPE
        $excel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);

        // Set judul file excel nya
        $excel->getActiveSheet(0)->setTitle("Laporan Data Petani");
        $excel->setActiveSheetIndex(0);

        // Proses file excel
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment; filename="Data Petani.xlsx"'); // Set nama file excel nya
        header('Cache-Control: max-age=0');

        $write = PHPExcel_IOFactory::createWriter($excel, 'Excel2007');
        $write->save('php://output');
    }
}
