<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Profil extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Profil_model');
        $this->load->library('upload');
    }

    /*
     * Listing of komoditas
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config['base_url'] = site_url('profil/index?');
        $this->pagination->initialize($config);
        $user_id = $this->session->userdata('user_id');
        $data['profil'] = $this->Profil_model->get_datapetani($user_id);

        $data['_view'] = 'profil/index';
        $this->load->view('layouts/main', $data);
    }

    function edit($id_petani)
    {
        // check if the petani exists before trying to edit it
        $data['profil'] = $this->Profil_model->get_datapetani($id_petani);
        
        if (isset($data['profil']['id_petani'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'jenis_kelamin' => $this->input->post('jenis_kelamin'),
                    'nama_petani' => $this->input->post('nama_petani'),
                    'tanggal_lahir' => $this->input->post('tanggal_lahir'),
                    'pendidikan_terakhir' => $this->input->post('pendidikan_terakhir'),
                    'nik' => $this->input->post('nik'),
                    'nomor_hp' => $this->input->post('nomor_hp'),
                    'alamat' => $this->input->post('alamat'),
                );

                $this->Profil_model->update_petani($id_petani, $params);
                redirect('profil/index');
            } else {
                $data['_view'] = 'profil/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The Profil you are trying to edit does not exist.');
    }

    /*
     * Adding a new komoditas
     */
}
