<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Paket_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get luasan by id_luasan
     */
    function get_paket($id_paket)
    {
        return $this->db->get_where('paket', array('id_paket' => $id_paket))->row_array();
    }

    /*
     * Get all paket count
     */
    function get_all_paket_count()
    {
        $this->db->from('paket');
        return $this->db->count_all_results();
    }

    /*
     * Get all paket
     */
    function get_all_paket($params = array())
    {
        $this->db->order_by('paket.id_paket', 'desc');
        $this->db->join('tbl_users', 'tbl_users.user_id=paket.created_by', 'left');
        if (isset($params) && !empty($params)) {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $user_id = $this->session->userdata('user_id');
        if ($user_id == '1') {
            return $this->db->get('paket')->result_array();
        } elseif ($user_id == '2') {
            return $this->db->get('paket')->result_array();
        } else {
            return $this->db->get_where('paket', array('paket.created_by' => $user_id))->result_array();
        }
    }

    /*
     * function to add new paket
     */
    function add_paket($params, $gambar)
    {
        $this->db->set('nama_program', $params['nama_program']);
        $this->db->set('kategori', $params['kategori']);
        $this->db->set('paket', $params['paket']);
        $this->db->set('hotel_mekkah', $params['hotel_mekkah']);
        $this->db->set('hotel_madinah', $params['hotel_madinah']);
        $this->db->set('bintang_mekkah', $params['bintang_mekkah']);
        $this->db->set('bintang_madinah', $params['bintang_madinah']);
        $this->db->set('matauang', $params['matauang']);
        $this->db->set('uang_muka', $params['uang_muka']);
        $this->db->set('matauangall', $params['matauangall']);
        $this->db->set('harga_paket', $params['harga_paket']);
        $this->db->set('sudah_termasuk', $params['sudah_termasuk']);
        $this->db->set('belum_termasuk', $params['belum_termasuk']);
        $this->db->set('paket_img', $gambar);
        $this->db->set('created_by', $params['created_by']);
        $this->db->insert('paket');
    }

    /*
     * function to update paket
     */
    function update_paket($id_paket, $params)
    {
        $this->db->where('id_paket', $id_paket);
        return $this->db->update('paket', $params);
    }

    /*
     * function to delete paket
     */
    function delete_paket($id_paket)
    {
        return $this->db->delete('paket', array('id_paket' => $id_paket));
    }
}
