<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Profil_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get komoditas by id_komoditas
     */
    function get_profil($user_id)
    {
        return $this->db->get_where('tbl_users',array('user_id'=>$user_id))->row_array();
    }

    function get_datapetani()
    {
        $id_petani=$this->session->userdata('id_petani');
        return $this->db->get_where('petani',array('id_petani'=>$id_petani))->row_array();
    }
    
    /*
     * Get all komoditas count
     */
    function get_all_profil_count()
    {
        $this->db->from('tbl_users');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all komoditas
     */
    function get_all_profil($params = array())
    {
        $this->db->order_by('user_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tbl_users')->result_array();
    }
        
    /*
     * function to add new komoditas
     */
    function add_profil($params)
    {
        $this->db->insert('tbl_users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update komoditas
     */
    function update_profil($user_id,$params)
    {
        $this->db->where('user_id',$user_id);
        return $this->db->update('tbl_users',$params);
    }

    function update_petani($id_petani,$params)
    {
        $this->db->where('id_petani',$id_petani);
        return $this->db->update('petani',$params);
    }
    
    /*
     * function to delete tbl_users
     */
    function delete_profil($user_id)
    {
        return $this->db->delete('tbl_users',array('user_id'=>$user_id));
    }
}
